const names = require('./4-names')
const {john,peter} = require('./4-names')
const sayHi = require("./5-utils")
const data = require("./alt_flavour")
require("./mind_grenade")
// console.log(data)
// sayHi(names.john)
// sayHi(names.peter)
// sayHi("susan")